;; Each new term in the Fibonacci sequence is generated by adding the 
;; previous two terms. By starting with 1 and 2, the first 10 terms will
;;  be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;; By considering the terms in the Fibonacci sequence whose values 
;; do not exceed four million, find the sum of the even-valued terms.


(defn fib-next-two [[a b]]
  [(+ a b)  (+ a b b)])


(fib-next-two [1 2])

(take 6 (iterate fib-next-two [1 2]))

